const questions = [
    // 1-20 (As originais)
    {
        theme: "DESIGUALDADE SOCIAL",
        question: "Qual obra sul-coreana aborda de forma visceral a luta de classes, servindo como excelente repertório para temas sobre estratificação e segregação urbana?",
        movie: "Parasita",
        year: "2019",
        country: "COREIA DO SUL",
        synopsis: "\"Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra sobre os abismos que separam as classes sociais na contemporaneidade.\"",
        options: ["Parasita", "Invasão Zumbi", "Oldboy"],
        correct: 0,
        hint: "O diretor é Bong Joon-ho e o filme fez história no Oscar.",
        explanation: "Parasita é uma metáfora perfeita para a desigualdade. Na redação, você pode relacioná-lo com a forma como a arquitetura e o espaço urbano refletem a divisão de classes e a invisibilidade social dos mais pobres.",
        image: "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "MEIO AMBIENTE",
        question: "Qual animação retrata um futuro onde a Terra se tornou um imenso lixão, sendo ideal para discutir consumismo exagerado e sustentabilidade?",
        movie: "Wall-E",
        year: "2008",
        country: "EUA",
        synopsis: "\"Após entulhar a Terra de lixo e poluir a atmosfera com gases tóxicos, a humanidade deixou o planeta... Apenas um pequeno robô de compactação de lixo foi deixado para trás.\"",
        options: ["O Lorax", "Wall-E", "A Era do Gelo"],
        correct: 1,
        hint: "O protagonista é um robô apaixonado que coleciona objetos antigos da humanidade.",
        explanation: "Wall-E ilustra as consequências do descarte inadequado de lixo e do consumismo desenfreado (representado pela megacorporação Buy n Large). Ótimo para redações sobre obsolescência programada e responsabilidade ambiental.",
        image: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "TECNOLOGIA E SOCIEDADE",
        question: "Nesta obra de ficção científica, um homem solitário se apaixona por um sistema operacional. Excelente para debater solidão na era digital e limites da IA.",
        movie: "Her (Ela)",
        year: "2013",
        country: "EUA",
        synopsis: "\"Um escritor solitário desenvolve uma relação improvável com um sistema operacional projetado para atender a todas as suas necessidades.\"",
        options: ["Ex Machina", "Blade Runner 2049", "Her (Ela)"],
        correct: 2,
        hint: "O protagonista escreve cartas emocionais para outras pessoas como profissão.",
        explanation: "Her explora a dependência tecnológica e o isolamento social contemporâneo. Use na redação para discutir como as redes sociais e a IA, embora conectem o mundo, podem criar relações superficiais e aumentar a solidão humana.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SAÚDE MENTAL",
        question: "Qual filme aborda a negligência estatal com a saúde mental e como a marginalização de indivíduos pode gerar violência na sociedade?",
        movie: "Coringa",
        year: "2019",
        country: "EUA",
        synopsis: "\"Um comediante falido e ignorado pela sociedade lida com distúrbios mentais, o que o leva a uma espiral de violência e revolução social.\"",
        options: ["Coringa", "Clube da Luta", "O Iluminado"],
        correct: 0,
        hint: "O protagonista trabalha vestido de palhaço e sofre de um transtorno neurológico.",
        explanation: "Coringa é um forte repertório sobre a falta de assistência psiquiátrica (negligência estatal) e a exclusão social. Pode embasar argumentos sobre como a sociedade estigmatiza doentes mentais em vez de acolhê-los.",
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "EDUCAÇÃO",
        question: "Baseado em fatos reais, este filme mostra uma professora que transforma a vida de alunos marginalizados através da literatura e empatia.",
        movie: "Escritores da Liberdade",
        year: "2007",
        country: "EUA",
        synopsis: "\"Uma jovem professora inspira sua classe de estudantes em risco a aprender tolerância, aplicar-se aos estudos e prosseguir para a educação superior.\"",
        options: ["Sociedade dos Poetas Mortos", "Escritores da Liberdade", "Mentes Perigosas"],
        correct: 1,
        hint: "Eles escrevem diários sobre suas duras experiências com violência, racismo e preconceito.",
        explanation: "Escritores da Liberdade demonstra o papel transformador da educação e a importância de professores motivados. Use para redações sobre evasão escolar, violência urbana e o poder da leitura na formação crítica.",
        image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "RACISMO",
        question: "Nesta obra de terror psicológico, o racismo estrutural é exposto através da apropriação e exploração de corpos negros pela elite.",
        movie: "Corra! (Get Out)",
        year: "2017",
        country: "EUA",
        synopsis: "\"Um jovem negro visita a família de sua namorada branca em uma propriedade isolada e descobre um segredo perturbador.\"",
        options: ["Nós", "Corra!", "Infiltrado na Klan"],
        correct: 1,
        hint: "O protagonista é um fotógrafo que é hipnotizado através de uma xícara de chá.",
        explanation: "Corra! é uma crítica afiada ao racismo velado e à objetificação. Serve como repertório para discutir como o preconceito persiste de formas sofisticadas e perversas na sociedade contemporânea.",
        image: "https://images.unsplash.com/photo-1531265726475-52ad60219627?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SISTEMA PRISIONAL",
        question: "Qual clássico do cinema retrata a vida em uma penitenciária, perfeito para debater a ressocialização (ou a falta dela) de ex-detentos?",
        movie: "Um Sonho de Liberdade",
        year: "1994",
        country: "EUA",
        synopsis: "\"Dois homens aprisionados se unem ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.\"",
        options: ["À Espera de um Milagre", "Carandiru", "Um Sonho de Liberdade"],
        correct: 2,
        hint: "O protagonista foi condenado injustamente pela morte da esposa e usa seus conhecimentos em contabilidade na prisão.",
        explanation: "A obra evidencia as falhas estruturais do sistema penitenciário e o processo de 'institucionalização', onde o indivíduo perde a capacidade de viver em liberdade. Ótimo para temas sobre superlotação e ressocialização.",
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "VIOLÊNCIA URBANA",
        question: "Este aclamado filme nacional expõe a realidade do tráfico de drogas e a espiral de violência nas favelas do Rio de Janeiro.",
        movie: "Cidade de Deus",
        year: "2002",
        country: "BRASIL",
        synopsis: "\"Nas favelas do Rio, dois caminhos divergem enquanto um aspirante a fotógrafo tenta sobreviver, e outros cedem à guerra das drogas.\"",
        options: ["Tropa de Elite", "Cidade de Deus", "Pixote"],
        correct: 1,
        hint: "A história é narrada por Buscapé e acompanha a ascensão de Zé Pequeno.",
        explanation: "Cidade de Deus ilustra a ausência do Estado nas periferias, o aliciamento de menores pelo tráfico e o ciclo vicioso da criminalidade. Repertório essencial para redações sobre segurança pública e desigualdade no Brasil.",
        image: "https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "PAPEL DA MULHER E RACISMO",
        question: "Baseado em fatos, narra a história de cientistas negras na NASA. Excelente para temas sobre machismo, racismo e inserção da mulher na ciência.",
        movie: "Estrelas Além do Tempo",
        year: "2016",
        country: "EUA",
        synopsis: "\"A história de uma equipe de mulheres matemáticas afro-americanas que desempenharam um papel vital na NASA nos primeiros anos do programa espacial.\"",
        options: ["Estrelas Além do Tempo", "A Cor Púrpura", "Histórias Cruzadas"],
        correct: 0,
        hint: "As protagonistas enfrentam banheiros segregados e falta de reconhecimento num ambiente dominado por homens.",
        explanation: "O filme combate o apagamento histórico de minorias e mostra a dupla discriminação (gênero e raça). Ideal para argumentar sobre a necessidade de representatividade feminina nas áreas de Ciência e Tecnologia.",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "MANIPULAÇÃO DA MÍDIA",
        question: "A vida de um homem é transmitida 24h por dia como um reality show sem que ele saiba. Obra essencial para debater os limites do entretenimento e privacidade.",
        movie: "O Show de Truman",
        year: "1998",
        country: "EUA",
        synopsis: "\"Um vendedor de seguros descobre que toda a sua vida é, na verdade, um reality show de televisão consumido globalmente.\"",
        options: ["Black Mirror: Bandersnatch", "O Show de Truman", "Matrix"],
        correct: 1,
        hint: "Interpretado por Jim Carrey, o personagem percebe padrões estranhos em sua cidade artificial perfeita.",
        explanation: "Uma poderosa alegoria sobre a espetacularização da vida privada e a manipulação midiática. Perfeito para temas sobre exposição nas redes sociais, fake news e a busca incessante por audiência.",
        image: "https://images.unsplash.com/photo-1586339949916-3e9f27a3c306?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "PADRÕES DE BELEZA",
        question: "Qual sátira premiada retrata as pressões psicológicas e os sacrifícios exigidos para se encaixar nos cruéis padrões estéticos?",
        movie: "A Substância",
        year: "2024",
        country: "EUA / REINO UNIDO",
        synopsis: "\"Uma celebridade em declínio decide usar uma droga do mercado negro que replica células para criar temporariamente uma versão mais jovem de si mesma.\"",
        options: ["O Diabo Veste Prada", "A Substância", "Cisne Negro"],
        correct: 1,
        hint: "É um filme de 'body horror' onde a protagonista divide seu tempo entre sua versão atual e uma versão mais jovem.",
        explanation: "A Substância critica a obsessão cultural pela juventude e os efeitos destrutivos dos inalcançáveis padrões de beleza sobre a saúde mental e física, impulsionados pela indústria do entretenimento.",
        image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "AUTORITARISMO E CENSURA",
        question: "Neste filme, numa distopia totalitária, um vigilante mascarado luta contra um governo opressor. Forte repertório para liberdade de expressão e censura.",
        movie: "V de Vingança",
        year: "2005",
        country: "EUA / REINO UNIDO",
        synopsis: "\"Em um futuro britânico sob um regime fascista tirânico, um combatente da liberdade mascarado planeja derrubá-lo.\"",
        options: ["Jogos Vorazes", "V de Vingança", "1984"],
        correct: 1,
        hint: "O protagonista usa uma máscara de Guy Fawkes que virou símbolo mundial de protestos como o Anonymous.",
        explanation: "Ilustra perfeitamente os perigos de governos autoritários que utilizam o medo para justificar a perda de liberdades civis, censurar a mídia e oprimir a população civil.",
        image: "https://images.unsplash.com/photo-1533514114760-4389f572ae26?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ÉTICA NA CIÊNCIA",
        question: "Filme que aborda os dilemas morais da criação da bomba atômica, essencial para discutir os limites éticos do desenvolvimento científico.",
        movie: "Oppenheimer",
        year: "2023",
        country: "EUA",
        synopsis: "\"A história do cientista americano J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica no Projeto Manhattan.\"",
        options: ["O Jogo da Imitação", "A Teoria de Tudo", "Oppenheimer"],
        correct: 2,
        hint: "Dirigido por Christopher Nolan, foca no peso da culpa do seu protagonista após sua criação.",
        explanation: "Oppenheimer levanta o debate crucial de que a inovação tecnológica não deve estar dissociada da responsabilidade ética. Use para temas sobre IA armamentista, biotecnologia e impactos de invenções na humanidade.",
        image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "CONSUMISMO E ALIENAÇÃO",
        question: "Qual longa critica o materialismo crônico do homem moderno, sugerindo que 'as coisas que você possui acabam possuindo você'?",
        movie: "Clube da Luta",
        year: "1999",
        country: "EUA",
        synopsis: "\"Um trabalhador de escritório deprimido e insone procura uma saída para a sua vida vazia formando um clube clandestino de lutas.\"",
        options: ["Clube da Luta", "O Lobo de Wall Street", "Psicopata Americano"],
        correct: 0,
        hint: "A primeira regra é não falar sobre ele.",
        explanation: "A obra desconstrói o ideal de felicidade atrelado ao consumo imposto pelo capitalismo. Um ótimo repertório para abordar a futilidade das compras excessivas, ansiedade moderna e saúde mental.",
        image: "https://images.unsplash.com/photo-1516086847842-832f01f8072b?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "RELAÇÕES DE TRABALHO",
        question: "Nesta obra-prima de Chaplin, são feitas duras críticas às condições subumanas do trabalho nas fábricas e à alienação da Revolução Industrial.",
        movie: "Tempos Modernos",
        year: "1936",
        country: "EUA",
        synopsis: "\"O Vagabundo luta para viver na moderna sociedade industrial altamente mecanizada.\"",
        options: ["O Grande Ditador", "Tempos Modernos", "Metrópolis"],
        correct: 1,
        hint: "O protagonista passa o dia todo apertando parafusos em uma linha de montagem e acaba enlouquecendo.",
        explanation: "Clássico atemporal para abordar a exploração do trabalhador, a substituição do homem pela máquina e a precarização do trabalho (que pode ser conectada à atual 'uberização' e Burnout).",
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ENVELHECIMENTO E DEMÊNCIA",
        question: "Qual filme retrata com genialidade a perspectiva confusa de um idoso sofrendo com demência, ideal para debater amparo familiar e longevidade?",
        movie: "Meu Pai",
        year: "2020",
        country: "REINO UNIDO",
        synopsis: "\"Um homem idoso recusa a ajuda de sua filha e começa a duvidar da sua mente e da própria realidade do tempo e espaço à sua volta.\"",
        options: ["Amour", "Meu Pai", "Up: Altas Aventuras"],
        correct: 1,
        hint: "A genialidade do filme está em fazer o espectador se sentir tão confuso quanto o protagonista (Anthony Hopkins).",
        explanation: "Meu Pai expõe os desafios do cuidado aos idosos e o impacto das doenças neurodegenerativas na família. Excelente para redações sobre políticas de amparo à terceira idade e abandono afetivo.",
        image: "https://images.unsplash.com/photo-1513159446162-54eb8bdaa79e?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "INTOLERÂNCIA RELIGIOSA",
        question: "Esta animação narra a infância de uma garota iraniana durante a Revolução Islâmica, mostrando a perda de liberdades sob o fundamentalismo.",
        movie: "Persépolis",
        year: "2007",
        country: "FRANÇA / IRÃ",
        synopsis: "\"Uma garota de espírito livre cresce em meio à guerra e ao radicalismo religioso que muda drasticamente as leis do seu país.\"",
        options: ["Persépolis", "O Menino e o Mundo", "Túmulo dos Vagalumes"],
        correct: 0,
        hint: "O visual do filme é majoritariamente em preto e branco, assim como a HQ original francesa.",
        explanation: "Persépolis evidencia como o extremismo religioso aniquila liberdades individuais e direitos civis, especialmente das mulheres. Forte repertório para temas sobre fundamentalismo, tolerância e estado laico.",
        image: "https://images.unsplash.com/photo-1542601098-8fc114e148e2?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ADOÇÃO E IDENTIDADE",
        question: "Baseado em fatos, mostra um jovem indiano adotado por australianos tentando reencontrar sua família biológica através do Google Earth.",
        movie: "Lion: Uma Jornada para Casa",
        year: "2016",
        country: "AUSTRÁLIA / REINO UNIDO",
        synopsis: "\"Um menino se perde na Índia, é adotado na Austrália e, 25 anos depois, tenta encontrar o caminho de volta usando tecnologias de mapa.\"",
        options: ["Extraordinário", "À Procura da Felicidade", "Lion: Uma Jornada para Casa"],
        correct: 2,
        hint: "Dev Patel interpreta a versão adulta do protagonista que busca desesperadamente sua mãe biológica.",
        explanation: "Lion levanta questões sobre os traumas da perda, a burocracia/falhas do sistema de adoção internacional e a importância da busca por raízes culturais na construção da identidade psicológica.",
        image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "IMIGRAÇÃO E REFUGIADOS",
        question: "Qual documentário em animação conta a angustiante jornada de um refugiado afegão, sendo ótimo para temas de crises humanitárias e xenofobia?",
        movie: "Flee - Nenhum Lugar para Chamar de Lar",
        year: "2021",
        country: "DINAMARCA",
        synopsis: "\"A verdadeira história de um homem, prestes a se casar, forçado a revelar como fugiu do Afeganistão de forma ilegal para sobreviver.\"",
        options: ["Flee", "Klaus", "Divertida Mente"],
        correct: 0,
        hint: "A obra foi indicada simultaneamente ao Oscar em categorias de Animação, Documentário e Filme Internacional.",
        explanation: "Flee é perfeito para discutir crises humanitárias contemporâneas, o desamparo legal dos apátridas e a xenofobia enfrentada por essas pessoas ao tentarem asilo e dignidade em outros países.",
        image: "https://images.unsplash.com/photo-1522032470701-a1e4a11fde8f?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "DEPENDÊNCIA QUÍMICA",
        question: "Um retrato devastador de como diferentes tipos de vícios (heroína e até remédios de emagrecer) destroem famílias. Útil para debater o problema das drogas.",
        movie: "Requiem para um Sonho",
        year: "2000",
        country: "EUA",
        synopsis: "\"As ilusões de quatro pessoas em busca de um sonho são destruídas quando seus vícios se aprofundam incontrolavelmente.\"",
        options: ["Trainspotting", "Requiem para um Sonho", "Christiane F."],
        correct: 1,
        hint: "Possui uma trilha sonora tensa (Lux Aeterna) e edições rápidas que simulam o efeito dos entorpecentes.",
        explanation: "Mostra que a dependência química é uma doença que afeta o indivíduo e sua família. Pode ser usado para argumentar que a drogadição é uma grave questão de saúde mental e pública, agravada pelo isolamento.",
        image: "https://images.unsplash.com/photo-1616441369792-56453d4c622d?q=80&w=800&auto=format&fit=crop"
    },
    // Novas 30 questões:
    {
        theme: "CAPITALISMO E DESIGUALDADE",
        question: "Nesta distopia, a sociedade é dividida em distritos que devem enviar jovens para lutar até a morte como forma de entretenimento e controle social.",
        movie: "Jogos Vorazes",
        year: "2012",
        country: "EUA",
        synopsis: "\"Katniss Everdeen voluntaria-se para tomar o lugar de sua irmã mais nova no evento anual televisionado onde adolescentes lutam até a morte.\"",
        options: ["Divergente", "Maze Runner", "Jogos Vorazes"],
        correct: 2,
        hint: "O símbolo da revolução é um pássaro chamado Tordo.",
        explanation: "Pode ser usado para discutir o pão e circo moderno, onde a mídia mascara os problemas sociais (desigualdade dos distritos x Capital) com entretenimento.",
        image: "https://images.unsplash.com/photo-1533514114760-4389f572ae26?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "HOMOFOBIA E PRECONCEITO",
        question: "Qual aclamado filme retrata o amor proibido entre dois vaqueiros, enfrentando o machismo estrutural e a homofobia na sociedade americana?",
        movie: "O Segredo de Brokeback Mountain",
        year: "2005",
        country: "EUA",
        synopsis: "\"A história do relacionamento complexo e secreto entre dois caubóis ao longo de duas décadas.\"",
        options: ["Me Chame Pelo Seu Nome", "O Segredo de Brokeback Mountain", "Moonlight"],
        correct: 1,
        hint: "Foi dirigido por Ang Lee e estrelado por Heath Ledger e Jake Gyllenhaal.",
        explanation: "Repertório essencial para discutir as raízes do preconceito, a repressão sexual e as consequências trágicas da homofobia na saúde mental e integridade física de pessoas LGBTQIA+.",
        image: "https://images.unsplash.com/photo-1520698188168-b7eb711181ec?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "CULTURA DO CANCELAMENTO",
        question: "Neste filme, um professor de creche é falsamente acusado de abuso, mostrando como a histeria coletiva pode destruir a vida de uma pessoa.",
        movie: "A Caça",
        year: "2012",
        country: "DINAMARCA",
        synopsis: "\"A vida de um professor é despedaçada por uma mentira inocente que se espalha rapidamente pela sua pequena comunidade.\"",
        options: ["O Leitor", "A Caça", "A Onda"],
        correct: 1,
        hint: "O protagonista é interpretado por Mads Mikkelsen.",
        explanation: "Perfeito para temas sobre cultura do cancelamento, linchamento virtual, presunção de inocência e os danos irreparáveis de fake news e boatos não verificados.",
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "EXPLORAÇÃO ANIMAL E ALIMENTAÇÃO",
        question: "Qual documentário perturbador expõe as práticas cruéis e o impacto ambiental das grandes corporações da indústria agropecuária?",
        movie: "Cowspiracy",
        year: "2014",
        country: "EUA",
        synopsis: "\"Um documentário que investiga o impacto da agropecuária no meio ambiente e questiona as políticas de organizações ambientais.\"",
        options: ["Super Size Me", "Cowspiracy", "O Dilema das Redes"],
        correct: 1,
        hint: "O foco principal é o impacto ambiental da criação de gado.",
        explanation: "Excelente para debater o impacto do agronegócio nas mudanças climáticas, desmatamento, e o consumo sustentável de recursos naturais.",
        image: "https://images.unsplash.com/photo-1551887373-6edba6dac3d2?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "POLITIZAÇÃO DA MÍDIA E FAKE NEWS",
        question: "Uma sátira onde cientistas descobrem que um cometa vai destruir a Terra, mas o governo e a mídia minimizam o problema por interesses políticos.",
        movie: "Não Olhe Para Cima",
        year: "2021",
        country: "EUA",
        synopsis: "\"Dois astrônomos tentam alertar o mundo sobre um cometa que destruirá o planeta, mas ninguém parece se importar.\"",
        options: ["Não Olhe Para Cima", "O Dia Depois de Amanhã", "Armageddon"],
        correct: 0,
        hint: "Estrelado por Leonardo DiCaprio e Jennifer Lawrence.",
        explanation: "Crítica contundente ao negacionismo científico (como visto na pandemia ou nas mudanças climáticas), politização de tragédias e ao papel da mídia que prioriza o entretenimento superficial.",
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SISTEMA EDUCACIONAL E PRESSÃO",
        question: "Neste filme clássico de Robin Williams, um professor não convencional usa poesia para inspirar os alunos a desafiarem o conformismo da escola.",
        movie: "Sociedade dos Poetas Mortos",
        year: "1989",
        country: "EUA",
        synopsis: "\"Um professor de inglês não ortodoxo inspira seus alunos a aproveitar o dia e tornar suas vidas extraordinárias.\"",
        options: ["Gênio Indomável", "Sociedade dos Poetas Mortos", "Whiplash"],
        correct: 1,
        hint: "A frase icônica do filme é 'Carpe Diem' (aproveite o dia).",
        explanation: "Ideal para criticar o sistema educacional tradicional, conteudista e opressor, e discutir a importância da autonomia, criatividade e pensamento crítico na juventude.",
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "CAPACITISMO E INCLUSÃO",
        question: "O filme acompanha a amizade improvável entre um aristocrata tetraplégico e seu cuidador recém-saído da prisão, abordando inclusão e empatia.",
        movie: "Intocáveis",
        year: "2011",
        country: "FRANÇA",
        synopsis: "\"Após ficar tetraplégico em um acidente de parapente, um aristocrata contrata um jovem do projeto habitacional para ser seu cuidador.\"",
        options: ["Intocáveis", "Como Eu Era Antes de Você", "A Teoria de Tudo"],
        correct: 0,
        hint: "É um dos filmes franceses de maior sucesso internacional.",
        explanation: "Combate o capacitismo ao mostrar que pessoas com deficiência não querem pena, mas sim serem tratadas com dignidade, humanidade e respeito.",
        image: "https://images.unsplash.com/photo-1574326588214-7221e7dd19cc?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SAÚDE PÚBLICA E PANDEMIAS",
        question: "Muito antes da Covid-19, este filme previu com assustadora precisão a rápida propagação de um vírus letal e o colapso dos sistemas de saúde.",
        movie: "Contágio",
        year: "2011",
        country: "EUA",
        synopsis: "\"Profissionais de saúde, governos e cidadãos comuns lutam contra uma pandemia global mortal e o pânico que se espalha mais rápido que o próprio vírus.\"",
        options: ["Epidemia", "Guerra Mundial Z", "Contágio"],
        correct: 2,
        hint: "Mostra a origem do vírus a partir do contato entre um morcego e um porco.",
        explanation: "Serve como repertório para discutir o impacto devastador de pandemias, o medo, a desinformação (fake news sobre curas milagrosas) e a importância da cooperação internacional.",
        image: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "TRABALHO INFANTIL",
        question: "Uma jovem afegã é forçada a se disfarçar de menino para sustentar sua família sob o domínio do Talibã, destacando a vulnerabilidade infantil.",
        movie: "A Ganha-Pão",
        year: "2017",
        country: "CANADÁ / IRLANDA",
        synopsis: "\"Uma menina de 11 anos corta o cabelo e se veste de menino para poder trabalhar e sustentar sua família após seu pai ser preso injustamente.\"",
        options: ["O Caçador de Pipas", "A Ganha-Pão", "Valente"],
        correct: 1,
        hint: "É uma animação produzida por Angelina Jolie.",
        explanation: "Útil para temas sobre direitos humanos, o machismo estrutural extremista, e o trabalho infantil forçado pela necessidade extrema.",
        image: "https://images.unsplash.com/photo-1504159506876-f8338247a14a?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "FASCISMO E MANIPULAÇÃO DE MASSAS",
        question: "Um professor tenta provar aos seus alunos que o fascismo ainda pode surgir hoje em dia, criando um movimento autoritário na escola.",
        movie: "A Onda",
        year: "2008",
        country: "ALEMANHA",
        synopsis: "\"Um experimento de um professor sobre ditadura sai do controle quando os alunos começam a formar uma unidade real com viés fascista.\"",
        options: ["O Experimento", "A Onda", "O Menino de Pijama Listrado"],
        correct: 1,
        hint: "Baseado em um experimento real ocorrido na Califórnia em 1967.",
        explanation: "Mostra a fragilidade da democracia e como o desejo humano por pertencimento e ordem pode facilmente levar à manipulação em massa e ao surgimento de regimes autocráticos.",
        image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "DIREITO AO ESQUECIMENTO E INTERNET",
        question: "Neste filme, pessoas podem apagar memórias dolorosas através de um procedimento médico, levantando questões sobre ética e identidade.",
        movie: "Brilho Eterno de Uma Mente Sem Lembranças",
        year: "2004",
        country: "EUA",
        synopsis: "\"Quando o relacionamento deles azeda, um casal passa por um procedimento médico para ter as memórias um do outro apagadas para sempre.\"",
        options: ["Efeito Borboleta", "A Origem", "Brilho Eterno de Uma Mente Sem Lembranças"],
        correct: 2,
        hint: "Estrelado por Jim Carrey e Kate Winslet, dirigido por Michel Gondry.",
        explanation: "Embora sci-fi, pode ser relacionado ao debate jurídico do 'Direito ao Esquecimento' na internet: o indivíduo tem o direito de apagar partes do seu passado do domínio público/tecnológico?",
        image: "https://images.unsplash.com/photo-1502444330042-d1a1ddf971b1?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "GRAVIDEZ NA ADOLESCÊNCIA",
        question: "O filme acompanha uma adolescente perspicaz que lida com uma gravidez não planejada, desafiando estigmas sociais.",
        movie: "Juno",
        year: "2007",
        country: "EUA",
        synopsis: "\"Diante de uma gravidez não planejada, uma adolescente independente e franca toma uma decisão incomum em relação ao bebê que está esperando.\"",
        options: ["Lady Bird", "Juno", "Meninas Malvadas"],
        correct: 1,
        hint: "A protagonista escolhe um casal 'perfeito' para adotar seu bebê.",
        explanation: "Pode embasar redações sobre a desmistificação da gravidez na adolescência, educação sexual e o impacto psicológico das responsabilidades precoces.",
        image: "https://images.unsplash.com/photo-1496302662116-35cc4f36df92?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ESPORTE COMO FERRAMENTA SOCIAL",
        question: "Nelson Mandela usa a equipe nacional de rúgbi para tentar unir uma África do Sul fraturada e recém-saída do Apartheid.",
        movie: "Invictus",
        year: "2009",
        country: "EUA",
        synopsis: "\"Nelson Mandela se une ao capitão do time de rúgbi da África do Sul em uma tentativa de unir o país durante a Copa do Mundo de Rúgbi de 1995.\"",
        options: ["Invictus", "Menina de Ouro", "Ali"],
        correct: 0,
        hint: "Dirigido por Clint Eastwood, com Morgan Freeman como Mandela.",
        explanation: "Repertório excepcional para demonstrar como o esporte é um fenômeno sociológico capaz de transcender barreiras raciais e promover integração nacional.",
        image: "https://images.unsplash.com/photo-1540981493580-8ea1113e9968?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SISTEMA FINANCEIRO E CRISE",
        question: "Qual filme explica a complexa crise financeira de 2008 de forma cômica e didática, mostrando investidores que apostaram contra o mercado imobiliário?",
        movie: "A Grande Aposta",
        year: "2015",
        country: "EUA",
        synopsis: "\"Quatro investidores descobrem as falhas no mercado imobiliário e decidem apostar contra os bancos antes do colapso econômico de 2008.\"",
        options: ["O Lobo de Wall Street", "Wall Street", "A Grande Aposta"],
        correct: 2,
        hint: "Traz Margot Robbie numa banheira de espuma explicando conceitos financeiros complexos.",
        explanation: "Critica a ganância corporativa, a falta de regulação estatal e a desigualdade do sistema bancário moderno.",
        image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "PRIVACIDADE DE DADOS",
        question: "Documentário que foca no escândalo da Cambridge Analytica e como dados de usuários do Facebook foram usados para manipular eleições.",
        movie: "Privacidade Hackeada",
        year: "2019",
        country: "EUA",
        synopsis: "\"O documentário explora o escândalo de dados da Cambridge Analytica através dos olhos de diferentes pessoas envolvidas.\"",
        options: ["O Dilema das Redes", "Privacidade Hackeada", "Snowden"],
        correct: 1,
        hint: "Foi lançado na Netflix e investiga diretamente a campanha de Trump e o Brexit.",
        explanation: "Repertório atualíssimo sobre vigilância digital, proteção de dados (LGPD) e como algoritmos afetam a democracia e a liberdade de escolha.",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "VALORIZAÇÃO DO SUS / SAÚDE",
        question: "Filme sobre o médico Drauzio Varella e seu trabalho de prevenção à AIDS no maior presídio do Brasil.",
        movie: "Carandiru",
        year: "2003",
        country: "BRASIL",
        synopsis: "\"Um médico se oferece para realizar um trabalho de prevenção à AIDS na maior prisão da América Latina.\"",
        options: ["Cidade de Deus", "Carandiru", "Tropa de Elite 2"],
        correct: 1,
        hint: "Termina com o trágico massacre de 1992.",
        explanation: "Importante para debater a importância das campanhas de saúde pública, o direito à saúde e as condições de vida no sistema carcerário brasileiro.",
        image: "https://images.unsplash.com/photo-1588775005506-cc94285743c3?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ETARISMO E MERCADO DE TRABALHO",
        question: "Um senhor de 70 anos volta ao mercado como estagiário em uma startup de moda, desafiando o preconceito contra idosos no ambiente corporativo.",
        movie: "Um Senhor Estagiário",
        year: "2015",
        country: "EUA",
        synopsis: "\"Um viúvo de 70 anos descobre que a aposentadoria não é tudo aquilo e decide voltar a trabalhar como estagiário em um site de moda.\"",
        options: ["Um Senhor Estagiário", "O Diabo Veste Prada", "Up: Altas Aventuras"],
        correct: 0,
        hint: "Estrelado por Robert De Niro e Anne Hathaway.",
        explanation: "Discute o idadismo (ou etarismo), mostrando que a experiência da terceira idade tem muito valor a agregar à sociedade e às novas gerações.",
        image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "VIOLÊNCIA POLICIAL",
        question: "Baseado em fatos, narra o assassinato não provocado de um jovem negro por um policial em uma estação de trem na véspera de Ano Novo.",
        movie: "Fruitvale Station",
        year: "2013",
        country: "EUA",
        synopsis: "\"A história do último dia de vida de Oscar Grant, antes de ser fatalmente baleado por policiais da BART em 2009.\"",
        options: ["Moonlight", "Fruitvale Station", "Infiltrado na Klan"],
        correct: 1,
        hint: "Foi o primeiro grande sucesso de Michael B. Jordan e do diretor Ryan Coogler.",
        explanation: "Pode ser usado para criticar o racismo institucionalizado e a truculência nas abordagens policiais a jovens negros da periferia.",
        image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "A INFLUÊNCIA DOS ALGORITMOS",
        question: "Documentário em que executivos arrependidos do Vale do Silício revelam como as redes sociais foram desenhadas para viciar o cérebro humano.",
        movie: "O Dilema das Redes",
        year: "2020",
        country: "EUA",
        synopsis: "\"Especialistas em tecnologia soam o alarme sobre as perigosas consequências das redes sociais no comportamento humano.\"",
        options: ["A Rede Social", "Privacidade Hackeada", "O Dilema das Redes"],
        correct: 2,
        hint: "Apresenta a frase: 'Se você não paga pelo produto, você é o produto'.",
        explanation: "Crucial para temas como saúde mental na era digital, dependência tecnológica, e como algoritmos causam polarização política e distorcem a realidade.",
        image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "MERITOCRACIA E PRIVILÉGIOS",
        question: "Um thriller onde a elite rica consegue comprar uma vacina ou a cura, levantando debates sobre até onde vai o privilégio em uma distopia futurista.",
        movie: "Elysium",
        year: "2013",
        country: "EUA",
        synopsis: "\"No ano de 2154, os muito ricos vivem em uma estação espacial imaculada e feita pelo homem, enquanto o resto da população arruinada reside em uma Terra superpovoada.\"",
        options: ["Mad Max", "Elysium", "Snowpiercer"],
        correct: 1,
        hint: "Protagonizado por Matt Damon e o ator brasileiro Wagner Moura.",
        explanation: "Critica o mito da meritocracia: em uma sociedade profundamente desigual, o acesso aos direitos básicos (como saúde e um ambiente limpo) se torna privilégio da classe dominante.",
        image: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "MOBILIDADE URBANA",
        question: "Série documental (ou o argumento em si) focado no colapso do trânsito e na necessidade de repensar as cidades para pessoas, não carros.",
        movie: "The Human Scale",
        year: "2012",
        country: "DINAMARCA",
        synopsis: "\"Documentário que questiona nossas suposições sobre a modernidade e mostra cidades repensando sua arquitetura para acomodar pessoas.\"",
        options: ["The Human Scale", "Cidades Sombrias", "Urbanized"],
        correct: 0,
        hint: "O diretor viaja pelo mundo para documentar o trabalho do arquiteto dinamarquês Jan Gehl.",
        explanation: "Útil para temas sobre o caos da mobilidade urbana no Brasil, a priorização de rodovias e carros particulares em detrimento do transporte público e ciclovias.",
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "DESASTRES AMBIENTAIS",
        question: "Qual documentário ou filme relata o impacto e negligência humana que causaram a destruição ambiental de Mariana ou eventos similares?",
        movie: "Chernobyl",
        year: "2019",
        country: "EUA / REINO UNIDO",
        synopsis: "\"Dramatização da tragédia da usina nuclear de 1986, evidenciando as mentiras estatais e as falhas humanas fatais.\"",
        options: ["Chernobyl", "O Impossível", "O Dia Depois de Amanhã"],
        correct: 0,
        hint: "É uma minissérie da HBO, mas conta como repertório fortíssimo de TV/Cinema.",
        explanation: "Pode ser associado aos desastres de Mariana e Brumadinho: evidencia como a negligência, a omissão do Estado e as mentiras corporativas geram tragédias ambientais irreversíveis.",
        image: "https://images.unsplash.com/photo-1616422285623-146b90713398?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "BULLYING",
        question: "Baseado no best-seller, aborda a história de um menino com deformidade facial que entra na escola pela primeira vez, enfrentando o preconceito e o bullying.",
        movie: "Extraordinário",
        year: "2017",
        country: "EUA",
        synopsis: "\"Baseado no best-seller do New York Times, este filme conta a inspiradora história de Auggie Pullman.\"",
        options: ["Ponte para Terabítia", "Extraordinário", "As Vantagens de Ser Invisível"],
        correct: 1,
        hint: "O protagonista usa um capacete de astronauta na cabeça.",
        explanation: "Excelente para redações sobre empatia escolar, bullying na infância e como a família e professores são fundamentais para o acolhimento das diferenças.",
        image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SANEAMENTO BÁSICO",
        question: "Nesta animação japonesa clássica, um espírito da sujeira (representando a poluição dos rios) invade uma casa de banhos.",
        movie: "A Viagem de Chihiro",
        year: "2001",
        country: "JAPÃO",
        synopsis: "\"Durante a mudança de sua família para o subúrbio, uma garota perambula por um mundo governado por deuses, bruxas e espíritos.\"",
        options: ["A Viagem de Chihiro", "Princesa Mononoke", "Ponyo"],
        correct: 0,
        hint: "O filme de Hayao Miyazaki ganhou o Oscar de Melhor Animação.",
        explanation: "A cena do Deus do Rio cheio de poluição urbana serve como metáfora para discutir a falta de saneamento básico e o descaso com o tratamento de resíduos na natureza.",
        image: "https://images.unsplash.com/photo-1542382156909-9240e3f22cb7?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "GORDOLFOBIA E AUTOESTIMA",
        question: "Nesta comédia, uma mulher obcecada com sua aparência bate a cabeça e passa a se ver como uma modelo, discutindo como a confiança altera o mundo.",
        movie: "Sexy por Acidente",
        year: "2018",
        country: "EUA",
        synopsis: "\"Uma mulher sofre uma pancada na cabeça e acorda acreditando que é a mulher mais bonita e capaz do planeta.\"",
        options: ["A Substância", "Pequena Miss Sunshine", "Sexy por Acidente"],
        correct: 2,
        hint: "Estrelado pela comediante Amy Schumer.",
        explanation: "Repertório leve, mas crítico, sobre a imposição estética feminina. Mostra como o sentimento de inadequação limita o potencial profissional e as relações sociais.",
        image: "https://images.unsplash.com/photo-1515347619152-1ec103a89073?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "ALIENAÇÃO PARENTAL E DIVÓRCIO",
        question: "Um drama aclamado que narra o esgotamento de um casamento e como o divórcio e o sistema legal afetam a relação do casal com o filho.",
        movie: "História de um Casamento",
        year: "2019",
        country: "EUA",
        synopsis: "\"O olhar incisivo e compassivo de Noah Baumbach sobre o rompimento de um casamento e como a família permanece unida.\"",
        options: ["Kramer vs Kramer", "História de um Casamento", "Manchester à Beira-Mar"],
        correct: 1,
        hint: "Estrelado por Scarlett Johansson e Adam Driver, e rendeu o Oscar de atriz coadjuvante para Laura Dern.",
        explanation: "Pode ser utilizado para discutir a complexidade das relações familiares contemporâneas, o papel do sistema jurídico em disputas e o impacto no bem-estar psicológico das crianças.",
        image: "https://images.unsplash.com/photo-1494774157365-9e04c6720e47?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SUPERALIMENTAÇÃO E FAST FOOD",
        question: "O documentarista decide passar um mês inteiro comendo exclusivamente McDonald's, em todas as refeições do dia, para comprovar os males do fast food.",
        movie: "Super Size Me",
        year: "2004",
        country: "EUA",
        synopsis: "\"A jornada de um mês de um homem comendo apenas comida do McDonald's e os efeitos severos que isso tem em sua saúde física e psicológica.\"",
        options: ["Food, Inc.", "Super Size Me", "Garfos em Vez de Facas"],
        correct: 1,
        hint: "O diretor/protagonista é Morgan Spurlock.",
        explanation: "Critica a responsabilidade das indústrias de fast food na epidemia de obesidade mundial, e como o marketing foca nas crianças para criar maus hábitos alimentares.",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "A IMPORTÂNCIA DA LEITURA",
        question: "Na Alemanha Nazista, uma jovem encontra consolo e rebeldia ao roubar livros, que passa a compartilhar com um judeu escondido em seu porão.",
        movie: "A Menina que Roubava Livros",
        year: "2013",
        country: "EUA / ALEMANHA",
        synopsis: "\"Enquanto é submetida aos horrores da Alemanha da Segunda Guerra, a jovem Liesel encontra consolo roubando livros.\"",
        options: ["O Menino do Pijama Listrado", "A Lista de Schindler", "A Menina que Roubava Livros"],
        correct: 2,
        hint: "A história é narrada pela Morte.",
        explanation: "Demonstra o livro como um refúgio e ferramenta de iluminação. Ótimo repertório para falar sobre como a leitura liberta do fanatismo e empodera indivíduos oprimidos.",
        image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "TRABALHO ESCRAVO CONTEMPORÂNEO",
        question: "Filme nacional de sucesso que retrata um homem que sai do nordeste para São Paulo e se depara com condições análogas à escravidão em um ferro velho.",
        movie: "7 Prisioneiros",
        year: "2021",
        country: "BRASIL",
        synopsis: "\"Para oferecer uma vida melhor à sua família no interior, o jovem Mateus aceita um emprego em um ferro-velho em São Paulo e acaba em uma teia de tráfico de pessoas.\"",
        options: ["Bacurau", "7 Prisioneiros", "Que Horas Ela Volta?"],
        correct: 1,
        hint: "Estrelado por Christian Malheiros e Rodrigo Santoro.",
        explanation: "Fundamental para discutir o tráfico de pessoas, a precarização extrema do trabalho e como a pobreza estrutural empurra cidadãos brasileiros para a escravidão moderna.",
        image: "https://images.unsplash.com/photo-1504280630045-8bb03b90040e?q=80&w=800&auto=format&fit=crop"
    },
    {
        theme: "SUPERVALORIZAÇÃO DA APARÊNCIA",
        question: "Um rapaz nasce deformado após ser amaldiçoado. Anos depois, numa feira de horrores do século XIX, ele é tratado como um monstro em virtude de sua aparência física assustadora.",
        movie: "O Homem Elefante",
        year: "1980",
        country: "EUA / REINO UNIDO",
        synopsis: "\"Um médico vitoriano resgata um homem gravemente desfigurado e tenta ajudá-lo a recuperar sua dignidade.\"",
        options: ["Freaks", "A Forma da Água", "O Homem Elefante"],
        correct: 2,
        hint: "Filme clássico do diretor David Lynch.",
        explanation: "Ótimo para abordar a aversão social àquilo que foge do padrão estético (Feiúra) e a falta de alteridade e empatia para com portadores de síndromes raras.",
        image: "https://images.unsplash.com/photo-1510165798993-90d346ffc1f6?q=80&w=800&auto=format&fit=crop"
    }
];
